@host = http://localhost:8080/api
# @host = https://iot-wildfire.mybluemix.net/api

###
GET {{host}}/data/history

###
POST {{host}}/data/upload
Content-Type: application/json

{
    "sensorId": 1,
    "co2": 60.00,
    "temperature": 30,
    "humidity": 54,
    "latitudeGPS": 152.52,
    "longitudeGPS": 90.32
}